config/routes.rb
Rails.application.routes.draw do
  resources :question_comments
  mount Ckeditor::Engine => '/ckeditor'
  root 'static_pages#home'
  devise_for :users, controllers: {registrations: 'registrations', confirmations: 'confirmations'}
  resources :taxis,:mathimas
  resources :suggested_posts
  resources :video_galleries do
    put :order, on: :collection
  end
  get 'users/:user_id/questions/:question_id/answers', to: 'answers#index'
  resources :users , only: [:index, :show], :shallow=>true do
    resources :questions do
      get :profile_index, on: :collection
    end
    resources :answers
    member do
      patch :enable_users
      patch :change_user_role
      patch :promote_to_teacher
    end
    get :search, on: :collection
  end
  get 'contact'=> 'static_pages#contact'
  get 'technology'=> 'static_pages#techno'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/taxi.rb
class Taxi < ApplicationRecord
  has_many :video_galleries
  has_many :mathimas
end

app/controllers/taxis_controller.rb
class TaxisController < ApplicationController
  before_action :collect_all
  before_action :authenticate_user!, except: [:show]
  load_and_authorize_resource

  # GET /taxis
  # GET /taxis.json
  def index
  end

  # GET /taxis/1
  # GET /taxis/1.json
  def show
  end

  # GET /taxis/new
  def new
  end

  # GET /taxis/1/edit
  def edit
  end

  # POST /taxis
  # POST /taxis.json
  def create
    @taxi = Taxi.new(taxi_params)

    respond_to do |format|
      if @taxi.save
        format.html { redirect_to @taxi, notice: 'Taxi was successfully created.' }
        format.json { render :show, status: :created, location: @taxi }
      else
        format.html { render :new }
        format.json { render json: @taxi.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /taxis/1
  # PATCH/PUT /taxis/1.json
  def update
    respond_to do |format|
      if @taxi.update(taxi_params)
        format.html { redirect_to @taxi, notice: 'Taxi was successfully updated.' }
        format.json { render :show, status: :ok, location: @taxi }
      else
        format.html { render :edit }
        format.json { render json: @taxi.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /taxis/1
  # DELETE /taxis/1.json
  def destroy
    @taxi.destroy
    respond_to do |format|
      format.html { redirect_to taxis_url, notice: 'Taxi was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.

    # Never trust parameters from the scary internet, only allow the white list through.
    def taxi_params
      params.require(:taxi).permit(:taxi, :mathima_id)
    end
end

app/helpers/taxis_helper.rb
module TaxisHelper
end

app/views/taxis/_form.html.erb
<div class="header-title white ken-burn" data-parallax="scroll" data-position="top" data-natural-height="550" data-natural-width="1920" data-image-src="../../../images/long-2.jpg">
  <div class="container">
    <div class="title-base">
       <h1>Προσθηκη Ταξης</h1>
    </div>
  </div>
</div>
<div class="section-empty text-center">
  <div class="container content">
    <h5 class="text-center">Προσθηκη τάξης συμπληρωμα φορμας</h5>
    <hr class="space m" />
  <div class="row">
    <div class="col-md-3">
    </div>
    <div class="col-md-6">
      <%= form_for(taxi,:html=>{class:'form-box'}) do |f| %>
        <% if taxi.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(taxi.errors.count, "error") %> prohibited this video_gallery from being saved:</h2>
            <ul>
              <% taxi.errors.full_messages.each do |message| %>
              <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
      </div>
    </div>

  <div class="row">
    <div class="col-md-12">
      <p>Τάξη</p>
      <%= f.text_field :taxi, placeholder: "προσθηκη τάξης", class:'form-control form-value' %>
    </div>
  </div>
  </div><!-- container -->
<hr class="space s" />
      <%= f.submit "Καταχώρηση", class:'btn-sm btn'%>
    <%end%>
</div><!-- section -->

app/views/taxis/edit.html.erb
<h1>Editing Taxi</h1>

<%= render 'form', taxi: @taxi %>

<%= link_to 'Show', @taxi %> |
<%= link_to 'Back', taxis_path %>

app/views/taxis/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Taxis</h1>

<table class="table table-responsive">
  <thead>
    <tr>
      <th>Taxi</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @taxis.each do |taxi| %>
      <tr>
        <td><%= taxi.taxi %></td>
        <td><%= link_to 'Show', taxi %></td>
        <td><%= link_to 'Edit', edit_taxi_path(taxi) %></td>
        <td><%= link_to 'Destroy', taxi, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Taxi', new_taxi_path %>

app/views/taxis/new.html.erb
<h1>New Taxi</h1>

<%= render 'form', taxi: @taxi %>

<%= link_to 'Back', taxis_path %>

app/views/taxis/show.html.erb
<div class="header-title white ken-burn" data-parallax="scroll" >
  <div class="container">
    <div class="title-base">
      <h1>Βιντεομαθηματα</h1>
    </div>
  </div>
</div>

<div class="section-empty">
  <div class="container content">
    <div class="row">
      <div class="col-md-3">
        <div class="title-base text-left">
          <hr class="anima">
          <h4> Βιντεομαθήματα </h4>
        </div>
      </div>
      <div class="col-md-4">
        <a class="btn btn-sm nav-justified" href="#">Μπορειτε να βρειτε τα υπολοιπα βιντεο κανοντας εγγραφη μονο με το email σας.Εντελώς δωρεάν!!</a>
      </div>
    </div><!-- row-->
  </div>
</div>
<% if !user_signed_in? %>
<div class"section-empty">
  <div class="row">
    <div class="col-md-8 col-center">
      <h3>Eπιλέξτε μάθημα</h3>
      <h2> <%=link_to "Σειρά των βίντεο" , video_galleries_path %></h2>
    </div>
  </div>
  <div class="container content">
    <div class="tab-box">
      <ul class="nav nav-tabs">
        <li class="active"> <a href="#<%=@taxi.mathimas.first.mathima.gsub(/\s+/,"")%>"><%= @taxi.mathimas.first.mathima.partition(" ").first%></a></li>
        <% @taxi.mathimas.drop(1).each  do |m|%>
          <li>
            <a href="#<%=m.mathima.gsub(/\s+/, "")%>"><%=m.mathima.partition(" ").first %></a>
          </li>
        <%end%>
      </ul>
         <% @video_galleries.where(:taxi=>@taxi.id).order('priority asc').each do |video_gallery| %>
           <% if video_gallery.mathima.mathima.partition(" ").first == @taxi.mathimas.first.mathima.partition(" ").first%>
             <div class="panel active" id="<%=video_gallery.mathima.mathima.gsub(/\s+/, "")%>" style="border-top-style: none; padding:5px;">
           <%else%>
             <div class="panel" id="<%=video_gallery.mathima.mathima.gsub(/\s+/, "")%>" style="border-top-style: none; padding:5px;">
           <%end%>
              <%= link_to "#{video_gallery.title}","##{video_gallery.id}"%>
                </div>
          <%end%>
      <% @video_galleries.where(:taxi=>@taxi.id).order('priority asc').each do |video_gallery| %>
        <% if video_gallery.mathima.mathima.partition(" ").first == @taxi.mathimas.first.mathima.partition(" ").first%>
          <div class="panel active" id="<%=video_gallery.mathima.mathima.gsub(/\s+/, "")%>">
        <%else%>
          <div class="panel" id="<%=video_gallery.mathima.mathima.gsub(/\s+/, "")%>">
        <%end%>
      <div class="row">
      <div class="col-md-4">
        <div id="<%=video_gallery.id%>">
          <%= link_to "https://youtube.com/watch?v=#{video_gallery.body}", class: ' lightbox thumbnail data-lightbox-anima="fade-top"' do%>
          <%= image_tag "https://img.youtube.com/vi/#{video_gallery.body}/0.jpg"%>
          <% if user_signed_in? && current_user.admin? %>
          <%= link_to 'Destroy', video_gallery, method: :delete, data: { confirm: 'Are you sure?' } %>   
          <%= link_to 'Edit', edit_video_gallery_path(video_gallery) %>
          <%end%>
        <%end%>
        </div>
      </div>
      <div class="col-md-8">
        <h2><%= video_gallery.title%></h2>
        <%= render 'questions/newform',question: Question.new, :locals => {:video_gallery => video_gallery.id}%>
      </div>
    </div>
    </div>
    <%end%>
  </div>
</div>
<%else%>
<div class"section-empty">
  <div class="container content">
  <div class="row">
    <div class="col-md-8 col-center">
      <h3>Eπιλέξτε μάθημα</h3>
    </div>
  </div>
    <div class="tab-box">
      <ul class="nav nav-tabs">
        <li class="active"> <a href="#<%=@taxi.mathimas.first.mathima.gsub(/\s+/,"")%>"><%= @taxi.mathimas.first.mathima.partition(" ").first%></a></li>
        <% @taxi.mathimas.drop(1).each  do |m|%>
          <li>
            <a href="#<%=m.mathima.gsub(/\s+/, "")%>"><%=m.mathima.partition(" ").first %></a>
          </li>
        <%end%>
      </ul>
         <% @video_galleries.where(:taxi=>@taxi.id).each do |video_gallery| %>
           <% if video_gallery.mathima.mathima.partition(" ").first == @taxi.mathimas.first.mathima.partition(" ").first%>
             <div class="panel active" id="<%=video_gallery.mathima.mathima.gsub(/\s+/, "")%>" style="border-top-style: none; padding:5px;">
           <%else%>
             <div class="panel" id="<%=video_gallery.mathima.mathima.gsub(/\s+/, "")%>" style="border-top-style: none; padding:5px;">
           <%end%>
              <%= link_to "#{video_gallery.title}","##{video_gallery.id}"%>
                </div>
          <%end%>
<% @taxi.mathimas.each do |m| %>
  <% m.video_galleries.where(:taxi=>@taxi.id).limit(5).each do |video_gallery| %>
        <% if video_gallery.mathima.mathima.partition(" ").first == @taxi.mathimas.first.mathima.partition(" ").first%>
          <div class="panel active" id="<%=video_gallery.mathima.mathima.gsub(/\s+/, "")%>">
        <%else%>
          <div class="panel" id="<%=video_gallery.mathima.mathima.gsub(/\s+/, "")%>">
        <%end%>
    <div class="row">
      <div class="col-md-4">
        <div id="<%=video_gallery.id%>">
        <%= link_to "https://youtube.com/watch?v=#{video_gallery.body}", class: ' lightbox thumbnail data-lightbox-anima="fade-top"' do%>
            <%= image_tag "https://img.youtube.com/vi/#{video_gallery.body}/0.jpg"%>
          <%end%>
        </div>
      </div>
      <div class="col-md-8">
        <h2><%= video_gallery.title%></h2>
      </div>
    </div>
    </div>
  <%end%>
  <% m.video_galleries.where(:taxi=>@taxi.id).drop(5).each do |video_gallery| %>
        <% if video_gallery.mathima.mathima.partition(" ").first == @taxi.mathimas.first.mathima.partition(" ").first%>
          <div class="panel active" id="<%=video_gallery.mathima.mathima.gsub(/\s+/, "")%>">
        <%else%>
          <div class="panel" id="<%=video_gallery.mathima.mathima.gsub(/\s+/, "")%>">
        <%end%>
    <div class="row">
      <div class="col-md-4">
        <div id="<%=video_gallery.id%>">
            <%= image_tag "https://img.youtube.com/vi/#{video_gallery.body}/0.jpg"%>
        </div>
      </div>
      <div class="col-md-8">
        <h2 style="color:#069"><%= video_gallery.title%></h2>
      </div>
    </div>
    </div>
  <%end%>
<%end%>
    </div>
  </div>
    </div>
  </div>
</div>
<%end%>
<%if user_signed_in? && current_user.admin?%>
  <%= link_to 'Προσθήκη Video', new_video_gallery_path %>
  <%= link_to 'Edit', edit_taxi_path(@taxi) %> |
  <%= link_to 'Back', taxis_path %>
<%end%>