config/routes.rb
Rails.application.routes.draw do
  resources :question_comments
  mount Ckeditor::Engine => '/ckeditor'
  root 'static_pages#home'
  devise_for :users, controllers: {registrations: 'registrations', confirmations: 'confirmations'}
  resources :taxis,:mathimas
  resources :suggested_posts
  resources :video_galleries do
    put :order, on: :collection
  end
  get 'users/:user_id/questions/:question_id/answers', to: 'answers#index'
  resources :users , only: [:index, :show], :shallow=>true do
    resources :questions do
      get :profile_index, on: :collection
    end
    resources :answers
    member do
      patch :enable_users
      patch :change_user_role
      patch :promote_to_teacher
    end
    get :search, on: :collection
  end
  get 'contact'=> 'static_pages#contact'
  get 'technology'=> 'static_pages#techno'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  ROLES = %i[admin teacher user]

  has_many :questions, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :question_comments

  after_save :populate_to_sphinx

  def admin?
    self.roles == "admin"
  end

  def teacher?
    self.roles == "teacher"
  end

  def active_for_authentication? 
    super && approved? 
  end 

  def inactive_message 
    if !approved? 
      :not_approved 
    else 
      super # Use whatever other message 
    end 
  end

  def populate_to_sphinx

        ThinkingSphinx::RealTime::Callbacks::RealTimeCallbacks.new(
              :user
                ).after_save self
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

   protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  def after_update_path_for(resource)
    users_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :collect_all
  before_filter :authenticate_user!
  before_filter :search
  load_and_authorize_resource

  def index
  end

  def show
  end

  def search
    if !params[:search].blank?
      @results = User.search(params[:search], :star=>true)
    end
  end

  def enable_users
    @user = User.find(params[:id])
    @user.approved = !@user.approved
    @user.save
    flash[:success] = @user.approved 
    redirect_to users_path
  end

  def change_user_role
    if @user.roles == 'user'
      @user.roles = 'admin'
      @user.save 
      flash[:success] = "user is now admin"
      redirect_to users_path
    else
      @user.roles = 'user'
      @user.save
      flash[:success] = "user is demoted to regular"
      redirect_to users_path
    end
  end
  def promote_to_teacher
    if @user.roles == 'user' || @user.roles == 'admin'
      @user.roles = 'teacher'
      @user.save
      flash[:success] = "user is now teacher"
      redirect_to users_path
    else
      @user.roles = 'user'
      @user.save
      flash[:success] = "user is now regular"
      redirect_to users_path
    end
  end

end

app/views/users/_searchresults.html.erb
<h3> Αποτελέσματα Αναζήτησης Χρηστών: </h3>
<% if @results != nil %>
  <table id="grid-basic" class="table table-condensed table-hover table-striped bootgrid-table">
    <thead>
      <tr>
        <th data-column-id="onoma">
          <a class="column-header-anchor sortable">
            <span class="text">Όνομα</span>
          </a>
        </th>
        <th data-column-id="eponimo">
          <a class="column-header-anchor sortable">
            <span class="text">Επίθετο</span>
          </a>
        </th>
        <th data-column-id="email">
          <a class="column-header-anchor sortable">
            <span class="text">Email</span>
          </a>
        </th>
      </tr>
    </thead>
    <tbody>
      <% @results.each do |result| %>
        <tr data-row-id="0">
          <td><%= link_to "#{result.onoma}", user_path(result) %></td>
          <td><%= result.eponimo %></td>
          <td><%= result.email %></td>
        </tr>
      <%end%>
    </tbody>
  </table>
<%else%>
  <h4> Δεν υπάρχουν αποτελέσματα αναζήτης </h4>
<%end%>

app/views/users/_sidemenu.html.erb
<div class="top-area">
<% if current_user.admin? || current_user.teacher? %>
<%= form_for search_users_path, :method=>'get', class: 'navbar-form' do %>
  <div class="input-group">
    <%= text_field_tag :search, params[:search],class: 'form-control', placeholder: 'Search Users' %>
    <div class="input-group-btn">
      <%= submit_tag "Search",:name=>nil,class: 'btn'%>
    </div>
  </div>
<%end%>
<%end%>
</div>
<br>
<aside class="sidebar mi-menu box-middle-container">
  <nav class="sidebar-nav box-middle">
    <ul class="side-menu ms-simple">
      <li>
        <%= link_to user_path(current_user) do %>
          <i class='fa fa-home'></i>Προβολη στοιχειων προφιλ <%= current_user.eponimo %>
        <%end%>
      </li>
      <li>
        <%= link_to edit_user_registration_path do %>
          <i class='fa fa-pencil' aria-hidden="true"></i>Αλλαγη στοιχειων
        <%end%>
      </li>
      <li>
        <% if params[:action] == "index"%>
          <%= link_to profile_index_user_questions_path(current_user) do %>
            <i class='fa fa-question' aria-hidden="true"></i>Προβολη των ερωτησεων του/της <%= current_user.eponimo%>
          <%end%>
        <%else%>
          <%= link_to profile_index_user_questions_path(@user) do %>
            <i class='fa fa-question' aria-hidden="true"></i>Προβολη των ερωτησεων του/της <%= @user.eponimo%>
          <%end%>
      <%end%>
      </li>
      <li>
        <% if current_user.admin?%>
          <%= link_to users_path do %>
            <i class='fa fa-check'></i>Ενεργοποιηση χρηστων
          <%end%>
        <%end%>
      </li>
    </ul>
  </nav>
</aside>

app/views/users/_titleheader.html.erb
<div class="header-title white ken-burn" data-parallax="scroll" >
  <div class="container">
    <div class="title-base">
      <h1>προφιλ χρηστη</h1>
    </div>
  </div>
</div>

<div class="section-empty">
  <div class="container content">
    <div class="row">
      <div class="col-md-3">
        <div class="title-base text-left">
          <hr class="anima">
          <h4><%= current_user.onoma %><br><%= current_user.eponimo %>  </h4>
        </div>
      </div>
      <div class="col-md-4">
        <a class="btn btn-sm nav-justified" href="#">Ρυθμιστε το προφιλ σας και δειτε τις ερωτησεις-απαντησεις σας, στα βιντεο</a>
      </div>
    </div><!-- row-->
  </div>
</div>

app/views/users/_userinfo.html.erb
<div class="row">
  <div class="col-xs-6">
    <h4> Όνομα Χρήστη </h4>
    <p><%= @user.onoma %></p>
  </div>
  <div class="col-xs-6">
    <h4> Επίθετο Χρήστη </h4>
    <p><%= @user.eponimo%></p>
  </div>
</div>

app/views/users/index.html.erb
<%= render 'titleheader' %>

<div class="section-empty">
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <%= render 'sidemenu' %>
      </div>
      <div class="col-md-4">
        <table class="table table-striped" id="manage-users">
          <thead>
            <tr>
              <th>Email</th>
              <th>Status</th>
              <th>Role</th>
            </tr>
          </thead>
          <tbody>
            <%- @users.each do |user| %>
              <tr id="user-<%= user.id %>">
                <td>
                  <%= user.email %>
                </td>
                <td class="status">
                  <%#= user.approved ? "Approved" : check_box_tag('approved', true, false) %>
                  <%= user.approved ? (link_to "Εχει ενεργοποιηθεί, πατήστε για απενεργοποίηση", enable_users_user_path(user),method: :patch, class: "btn btn-default btn-danger") : (link_to '#', enable_users_user_path(user), method: :patch , class: "btn btn-default btn-info") %>
                </td>
                <td>
                  <%= user.admin? ? (link_to "Ο χρήστης είναι διαχειριστης, πατήστε για αλλαγή", change_user_role_user_path(user), method: :patch, class: "btn btn-default") : (link_to "Πατήστε για να γίνει διαχειριστής αυτός ο χρήστης", change_user_role_user_path(user), method: :patch, class: "btn btn-default")%>
                </td>
                <td>
                  <%= user.teacher? ? (link_to "Ο χρήστης είναι καθηγητής, πατήστε για αλλαγή σε απλό χηστη", promote_to_teacher_user_path(user), method: :patch, class: "btn btn-default") : (link_to "Πατήστε για να γίνει καθηγητής αυτός ο χρήστης", promote_to_teacher_user_path(user), method: :patch, class: "btn btn-default") %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<%= render 'titleheader' %>

<div class="section-empty">
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <%= render 'sidemenu' %>
      </div>
      <div class="col-md-8">
        <%= render 'userinfo'%>
      </div>
    </div>
    <div class="row">
      <div class="col-md-4"></div>
      <div class="col-md-8">
        <%= render partial: 'searchresults' %>
      </div>
    </div>
  </div>
</div>