config/routes.rb
Rails.application.routes.draw do
  resources :question_comments
  mount Ckeditor::Engine => '/ckeditor'
  root 'static_pages#home'
  devise_for :users, controllers: {registrations: 'registrations', confirmations: 'confirmations'}
  resources :taxis,:mathimas
  resources :suggested_posts
  resources :video_galleries do
    put :order, on: :collection
  end
  get 'users/:user_id/questions/:question_id/answers', to: 'answers#index'
  resources :users , only: [:index, :show], :shallow=>true do
    resources :questions do
      get :profile_index, on: :collection
    end
    resources :answers
    member do
      patch :enable_users
      patch :change_user_role
      patch :promote_to_teacher
    end
    get :search, on: :collection
  end
  get 'contact'=> 'static_pages#contact'
  get 'technology'=> 'static_pages#techno'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/question_comment.rb
class QuestionComment < ApplicationRecord
  belongs_to :answer
  belongs_to :user
end

app/controllers/question_comments_controller.rb
class QuestionCommentsController < ApplicationController
  before_action :set_question_comment, only: [:show, :edit, :update, :destroy]

  # GET /question_comments
  # GET /question_comments.json
  def index
    @question_comments = QuestionComment.all
  end

  # GET /question_comments/1
  # GET /question_comments/1.json
  def show
  end

  # GET /question_comments/new
  def new
    @question_comment = QuestionComment.new
  end

  # GET /question_comments/1/edit
  def edit
  end

  # POST /question_comments
  # POST /question_comments.json
  def create
    @question_comment = QuestionComment.new(question_comment_params)

    respond_to do |format|
      if @question_comment.save
        format.html { redirect_to :back, notice: 'Question comment was successfully created.' }
        format.json { render :show, status: :created, location: @question_comment }
      else
        format.html { render :new }
        format.json { render json: @question_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /question_comments/1
  # PATCH/PUT /question_comments/1.json
  def update
    respond_to do |format|
      if @question_comment.update(question_comment_params)
        format.html { redirect_to @question_comment, notice: 'Question comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @question_comment }
      else
        format.html { render :edit }
        format.json { render json: @question_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /question_comments/1
  # DELETE /question_comments/1.json
  def destroy
    @question_comment.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Question comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question_comment
      @question_comment = QuestionComment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_comment_params
      params.require(:question_comment).permit(:answer_id, :body, :user_id)
    end
end

app/helpers/question_comments_helper.rb
module QuestionCommentsHelper
end

app/views/question_comments/_form.html.erb
<%= form_for(question_comment) do |f| %>
  <% if question_comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question_comment.errors.count, "error") %> prohibited this question_comment from being saved:</h2>

      <ul>
      <% question_comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.hidden_field :answer_id, :value => locals[:answer_id], class: 'form-control form-value' %>

  <div class="field">
    <%= f.label :body, "Σχολιάστε την απάντηση"%>
    <%= f.text_field :body, class: 'form-control form-value' %>
  </div>

  <div class="field">
    <%= f.hidden_field :user_id, :value => current_user.id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/question_comments/edit.html.erb
<h1>Editing Question Comment</h1>

<%= render 'form', question_comment: @question_comment %>

<%= link_to 'Show', @question_comment %> |
<%= link_to 'Back', question_comments_path %>

app/views/question_comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Question Comments</h1>

<table>
  <thead>
    <tr>
      <th>Question</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @question_comments.each do |question_comment| %>
      <tr>
        <td><%= question_comment.question_id %></td>
        <td><%= question_comment.body %></td>
        <td><%= link_to 'Show', question_comment %></td>
        <td><%= link_to 'Edit', edit_question_comment_path(question_comment) %></td>
        <td><%= link_to 'Destroy', question_comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question Comment', new_question_comment_path %>

app/views/question_comments/new.html.erb
<h1>New Question Comment</h1>

<%= render 'form', question_comment: @question_comment %>

<%= link_to 'Back', question_comments_path %>

app/views/question_comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Question:</strong>
  <%= @question_comment.question_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @question_comment.body %>
</p>

<%= link_to 'Edit', edit_question_comment_path(@question_comment) %> |
<%= link_to 'Back', question_comments_path %>