config/routes.rb
Rails.application.routes.draw do
  resources :question_comments
  mount Ckeditor::Engine => '/ckeditor'
  root 'static_pages#home'
  devise_for :users, controllers: {registrations: 'registrations', confirmations: 'confirmations'}
  resources :taxis,:mathimas
  resources :suggested_posts
  resources :video_galleries do
    put :order, on: :collection
  end
  get 'users/:user_id/questions/:question_id/answers', to: 'answers#index'
  resources :users , only: [:index, :show], :shallow=>true do
    resources :questions do
      get :profile_index, on: :collection
    end
    resources :answers
    member do
      patch :enable_users
      patch :change_user_role
      patch :promote_to_teacher
    end
    get :search, on: :collection
  end
  get 'contact'=> 'static_pages#contact'
  get 'technology'=> 'static_pages#techno'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/suggested_post.rb
class SuggestedPost < ApplicationRecord
  belongs_to :mathima
end

app/controllers/suggested_posts_controller.rb
class SuggestedPostsController < ApplicationController
  before_action :collect_all
  before_action :authenticate_user!, except: [:index]
  load_and_authorize_resource

  # GET /suggested_posts
  # GET /suggested_posts.json
  def index
    @suggested_posts = SuggestedPost.all
  end

  # GET /suggested_posts/1
  # GET /suggested_posts/1.json
  def show
  end

  # GET /suggested_posts/new
  def new
    @suggested_post = SuggestedPost.new
  end

  # GET /suggested_posts/1/edit
  def edit
  end

  # POST /suggested_posts
  # POST /suggested_posts.json
  def create
    @suggested_post = SuggestedPost.new(suggested_post_params)

    respond_to do |format|
      if @suggested_post.save
        format.html { redirect_to @suggested_post, notice: 'Suggested post was successfully created.' }
        format.json { render :show, status: :created, location: @suggested_post }
      else
        format.html { render :new }
        format.json { render json: @suggested_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /suggested_posts/1
  # PATCH/PUT /suggested_posts/1.json
  def update
    respond_to do |format|
      if @suggested_post.update(suggested_post_params)
        format.html { redirect_to @suggested_post, notice: 'Suggested post was successfully updated.' }
        format.json { render :show, status: :ok, location: @suggested_post }
      else
        format.html { render :edit }
        format.json { render json: @suggested_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /suggested_posts/1
  # DELETE /suggested_posts/1.json
  def destroy
    @suggested_post.destroy
    respond_to do |format|
      format.html { redirect_to suggested_posts_url, notice: 'Suggested post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def suggested_post_params
      params.require(:suggested_post).permit(:body, :mathima_id)
    end
end

app/helpers/suggested_posts_helper.rb
module SuggestedPostsHelper
end

app/views/suggested_posts/_form.html.erb
<%= form_for(suggested_post) do |f| %>
  <% if suggested_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(suggested_post.errors.count, "error") %> prohibited this suggested_post from being saved:</h2>

      <ul>
      <% suggested_post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-8">
      <div class="field">
        <%= f.label :body %> 
        <%= f.cktext_area :body %> 
      </div>
    </div>
    <div class="col-md-4">
      <div class="field">
        <%= f.label :mathima_id %> 
        <%= f.collection_select :mathima_id, @mathimas, :id, :mathima, {include_hidden: false}, {class: 'form-control form-value'} %> 
      </div>
    </div>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/suggested_posts/_posttable.html.erb
<div class="tab-box">
  <ul class="nav nav-tabs">
    <% @suggested_posts.each do |suggested_post| %>
      <li><a href="#<%= suggested_post.id %>"><%= suggested_post.mathima.mathima %></a></li>
    <% end %>
  </ul>

  <% @suggested_posts.each do |suggested_post| %>
    <div id="<%=suggested_post.id%>" class="panel">
      <%=sanitize suggested_post.body %>
      <% if user_signed_in? %>
        <%= link_to 'Show', suggested_post %></td>
        <%= link_to 'Edit', edit_suggested_post_path(suggested_post) %></td>
        <%= link_to 'Destroy', suggested_post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <%end%>
    </div>
  <% end %>
  <% if user_signed_in? && current_user.admin? %>
    <%= link_to 'New Suggested Post', new_suggested_post_path %>
  <% end %>
</div>

app/views/suggested_posts/_titleheader.html.erb
<div class="header-title white ken-burn" data-parallax="scroll" >
  <div class="container">
    <div class="title-base">
      <h1>Προτεινομενα Θεματα</h1>
    </div>
  </div>
</div>

<div class="section-empty">
  <div class="container content">
    <div class="row">
      <div class="col-md-3">
        <div class="title-base text-left">
          <hr class="anima">
          <h4> Θέματα και Απαντήσεις </h4>
        </div>
      </div>
      <div class="col-md-4">
        <a class="btn btn-sm nav-justified" href="#">Παρακατω θα βρειτε ολα τα προτεινομενα θεματα και τις απαντησεις  σε μορφη PDF </a>
      </div>
    </div><!-- row-->
  </div>
</div>

app/views/suggested_posts/edit.html.erb
<h1>Editing Suggested Post</h1>

<%= render 'form', suggested_post: @suggested_post %>

<%= link_to 'Show', @suggested_post %> |
<%= link_to 'Back', suggested_posts_path %>

app/views/suggested_posts/index.html.erb
<%= render 'titleheader' %>

<div class="section-empty">
  <div class="container">
    <%= render 'posttable'%>
  </div>
</div>

app/views/suggested_posts/new.html.erb
<h1>New Suggested Post</h1>

<%= render 'form', suggested_post: @suggested_post %>

<%= link_to 'Back', suggested_posts_path %>

app/views/suggested_posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%=sanitize @suggested_post.body %>
</p>

<p>
  <strong>Mathima:</strong>
  <%=@suggested_post.mathima_id %>
</p>

<%= link_to 'Edit', edit_suggested_post_path(@suggested_post) %> |
<%= link_to 'Back', suggested_posts_path %>